services:
    list-my-repos:
      image: "node:lts"
      container_name: "list-my-repos"
      user: "node"
      working_dir: "/usr/src/app"
      environment:
        - NODE_ENV=development
      volumes:
        - ./:/usr/src/app
      ports:
        - "80:80"
      command: "npm run dev -- --port 80"